[project]
name = "test-git"
version = "0.1.7"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
]

[dependency-groups]
dev = [
    "bump-my-version>=1.2.1",
]


